server:
  port: 8080
  compression:
    enabled: true
  shutdown: graceful

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: neocargo-marketplace
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 307147826842-u9d4u5urp5m4gkcs83buj2bdklguovd3.apps.googleusercontent.com
            client-secret: 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