server:
  port: 8080
  compression:
    enabled: true
  shutdown: graceful

spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: ${DB_HOST}
      port: 27017
      database: ${DB_HOST}
  security:
    oauth2:
      client:
        registration:
          authentik:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
        provider:
          authentik:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            issuer-uri: ${ISSUER_URI}
            user-info-uri: ${USER_INFO_URI}
            logout-uri: ${LOGOUT_URI}
  logging:
    level:
      org.springframework.security: ${LOG_LEVEL}
