access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

server:
  port: 8080
  compression:
    enabled: true
  shutdown: graceful

spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: ${DB_HOST}
      port: 27017
      database: neocargo-marketplace
  logging:
    level:
      org.springframework.security: ${LOG_LEVEL}