server:
  port: 8080
  compression:
    enabled: true
  shutdown: graceful

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: neocargo-marketplace
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: $_id
            client-secret: $_secret